### ISSUE TITLE
Need steps to pull it to local Archiva

### ISSUE THREAD

**Issue by aninda84** [craigburke/karma-gradle#11]
Hello,

Hope you are doing well and thanks for the wonderful plugin which is making our life easier.

I want to get the project in our local archiva but can't find it on Maven repo (I see some your other projects). Will you be able to help me with this?

Thanks,

Aninda

**Comment by craigburke** [comment]
Thanks for the kind words. You should be able to grab it from the gradle plugin repo:
https://plugins.gradle.org/plugin/com.craigburke.karma

**Comment by aninda84** [comment]
Hello,

Let me briefly describe my situation in details. I need to know if you have maven project created for it so that I can copy that in our enterprise archiva and use it.

Hope I am making sense.

Thanks,

Aninda

**Comment by craigburke** [comment]
The link above includes information on the maven repository this is published to (see the _Build script snippet for use in all Gradle versions_ part).

Maven repository: `https://plugins.gradle.org/m2/`
Dependency: `gradle.plugin.com.craigburke.gradle:karma-gradle:1.4.3`

I'm thinking that's all you should need (although I haven't used Archiva myself).

**Comment by aninda84** [comment]
Hello again,

Really appreciate your time and help. I have already checked the repo but it is redirecting to [JCenter](https://jcenter.bintray.com) when I am hitting Maven repository: https://plugins.gradle.org/m2/. When I following the trail, I saw some of your folders in [Jcenter Craigburke](https://jcenter.bintray.com/com/craigburke/gradle/), but unable to find the karma-gradle package.

If you don't mind, can you please provide me the exact path? Also when I downloaded the project from your Github, it doesn't have a pom.xml, so I can't run a mvn package either.

Appreciate again your help.

Aninda

**Comment by craigburke** [comment]
@aninda84 yeah it's a gradle project, you can run `./gradlew publishToMavenLocal` to build to project and publish it to your local maven repository (it'll generate the pom.xml as part of that process).

I've been considering publishing my gradle plugins to bintray and maven central in additional to Gradle's plugin repository anyway. I'll publish the latest version sometime today and point you at that if you don't have luck building locally.

**Comment by craigburke** [comment]
I'm going to close this. Feel free to reopen if you're still having trouble getting this published locally.
