### ISSUE TITLE
Gradle Karma Test Case

### ISSUE THREAD

**Issue by lovelynagpal** [craigburke/karma-gradle#12]
I am running karma test case using gradle. I am getting the below issue.
   *\* No such property: files for class: com.moowork.gradle.node.task.NodeTask_Decorated**

Here is my build.gradle file

buildscript {
  repositories {

```
jcenter()
mavenCentral()
maven {
        url "https://plugins.gradle.org/m2/"
    }
```

  }

  dependencies {
     classpath "com.eriwen:gradle-js-plugin:1.12.1"

  }
}

plugins {

```
id 'com.craigburke.karma' version '1.4.3'   
```

}

apply plugin: "com.eriwen.gradle.js"

karmaRun{ 

```
files= [
        //'JASMINE',
        //'JASMINE_ADAPTER',
        'test/lib/angular/angular.js',
        'test/lib/angular/angular-mocks.js',
        'test/lib/mock-ajax.js',
        'app/lib/bootstrap/*.js',
        'app/lib/edmDataManager.js',
        'app/lib/edmDataDefinition.js',
        'app/lib/dataMappingFramework.js',


        'test/unit/*.spec.js'


    ]

junitReporter = [outputDir: 'test-dir' ]
```

}

defaultTasks 'karma'

**Comment by craigburke** [comment]
Sorry I missed this one. You want to set that in the karma config block (not karmaRun).
