### ISSUE TITLE
Protractor

### ISSUE THREAD

**Issue by walshe** [craigburke/karma-gradle#14]
Hi,

I'm using grails 3 which uses your Karma/bower plugins.

Im looking to introduce Angular's 'Protractor' testing framework into my grails 3 proj so that I can perform some full end to end tests.

Any idea how I could do this easily with your plugin ?  thanks

**Comment by craigburke** [comment]
@walshe I just use Spock and Geb for my end to end tests for Angular apps and that's probably your easiest path. Checking out the grails docs on functional testing might be helpful: https://grails.github.io/grails-doc/latest/guide/testing.html#functionalTesting

You could probably get protractor installed and running using the node gradle plugin:
https://github.com/srs/gradle-node-plugin

I really wouldn't recommend that given how much work it would be to get it setup.

**Comment by walshe** [comment]
@craigburke 
I tried Spock and Geb but ran into timing and/or angular issues when I tried to test anything other that the page title (as Geb doesnt run Angular or the Javascript). Geb was fine for running other rest endpoints etc but I couldnt get it to drive the angular UI.
If you have achieved this I'd love to see an example though
