### ISSUE TITLE
Any update of this project?

### ISSUE THREAD

**Issue by harshild** [craigburke/karma-gradle#28]
Hi, I found your idea of having Karma plugin integrated to Gradle build excellent. But the project has not been updated for quite a while. Is it still being actively supported ??

**Comment by craigburke** [comment]
Yes, I'll try to work through the open issues and do a 1.5 releases sometime in the next week or two.

**Comment by harshild** [comment]
sounds good :)

let me know if there is some area i can contribute in. I have previously created gradle plugins so i am bit aware of it
