### ISSUE TITLE
Unable to execute karmaRun task

### ISSUE THREAD

**Issue by mbpolan** [craigburke/karma-gradle#3]
Hi,

I'm trying to use your plugin in my gradle project. I've applied the plugin and took defaults like suggested in the doc, but when I run `gradlew karmaRun`, it fails with the following exception during the nodeSetup task:

Caused by: java.io.FileNotFoundException: C:\Users\mike.gradle\nodejs\node-v4.2.3-windows-x64\bin\node.exe (The process cannot access the file because it is being used by another process)

I'm using Gradle 2.9. Any ideas?

[stacktrace.txt](https://github.com/craigburke/karma-gradle/files/96659/stacktrace.txt)

**Comment by mbpolan** [comment]
Never mind, turns out I had another node instance running already. Ugh, silly me. :)

**Comment by craigburke** [comment]
@kanadakid cool. Glad you figured it out! :+1:
